export const FETCH_SUPPLY = 'FETCH_SUPPLY';
export const FETCH_SUPPLY_SUCCESS = 'FETCH_SUPPLY_SUCCESS';
export const FETCH_SUPPLY_FAIL = 'FETCH_SUPPLY_FAIL';

export const ADD_SUPPLY = 'ADD_SUPPLY';
export const ADD_SUPPLY_SUCCESS = 'ADD_SUPPLY_SUCCESS';
export const ADD_SUPPLY_FAIL = 'ADD_SUPPLY_FAIL';

export const DELETE_SUPPLY = 'DELETE_SUPPLY';
export const DELETE_SUPPLY_SUCCESS = 'DELETE_SUPPLY_SUCCESS';
export const DELETE_SUPPLY_FAIL = 'DELETE_SUPPLY_FAIL';

export const UPDATE_SUPPLY = 'UPDATE_SUPPLY';
export const UPDATE_SUPPLY_SUCCESS = 'UPDATE_SUPPLY_SUCCESS';
export const UPDATE_SUPPLY_FAIL = 'UPDATE_SUPPLY_FAIL';
