export const ADD_SOURCEOFITEMS = 'ADD_SOURCEOFITEMS';
export const ADD_SOURCEOFITEMS_SUCCESS = 'ADD_SOURCEOFITEMS_SUCCESS';
export const ADD_SOURCEOFITEMS_FAIL = 'ADD_SOURCEOFITEMS_FAIL';

export const FETCH_SOURCEOFITEMS = 'FETCH_SOURCEOFITEMS';
export const FETCH_SOURCEOFITEMS_SUCCESS = 'FETCH_SOURCEOFITEMS_SUCCESS';
export const FETCH_SOURCEOFITEMS_FAIL = 'FETCH_SOURCEOFITEMS_FAIL';